//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace MakeChipInfoDB {
	using System.Collections.Generic;
	using System.Linq;
	using System.Xml.Serialization;
	
	
	/// <remarks/>
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
	[System.Xml.Serialization.XmlRootAttribute("device-information", Namespace="", IsNullable=false)]
	public partial class DeviceInformation
	{
		private decimal versionField;

		[System.Xml.Serialization.XmlElementAttribute("clockInfo")]
		public List<clockInfoType> ClockInfos = new List<clockInfoType>();

		[System.Xml.Serialization.XmlElementAttribute("device")]
		public List<deviceType> Devices;

		[System.Xml.Serialization.XmlElementAttribute("eem")]
		public List<EemType> Eems = new List<EemType>();

		[System.Xml.Serialization.XmlElementAttribute("eemClocks")]
		public List<eemClocksType> EemClocks = new List<eemClocksType>();

		[System.Xml.Serialization.XmlElementAttribute("eemTimer")]
		public List<eemTimerType> EemTimerItems = new List<eemTimerType>();

		[System.Xml.Serialization.XmlElementAttribute("eemTimers")]
		public List<eemTimersType> EemTimers = new List<eemTimersType>();

		[System.Xml.Serialization.XmlElementAttribute("extFeatures")]
		public List<extFeaturesType> ExtFeatures;

		[System.Xml.Serialization.XmlElementAttribute("features")]
		public List<featuresType> Features;

		[System.Xml.Serialization.XmlElementAttribute("funcletMap")]
		public List<funcletMapType> FuncletMaps = new List<funcletMapType>();

		[System.Xml.Serialization.XmlElementAttribute("functionMap")]
		public List<functionMapType> FunctionMaps = new List<functionMapType>();

		[System.Xml.Serialization.XmlElementAttribute("idCode")]
		public List<idCodeType> IdCodes = new List<idCodeType>();

		[System.Xml.Serialization.XmlElementAttribute("idMask")]
		public List<idCodeType> IdMasks = new List<idCodeType>();

		[System.Xml.Serialization.XmlElementAttribute("import")]
		public List<ImportType> Imports = new List<ImportType>();

		[System.Xml.Serialization.XmlElementAttribute("memory")]
		public List<MemoryType> Memories;

		[System.Xml.Serialization.XmlElementAttribute("memoryLayout")]
		public List<memoryLayoutType> MemoryLayouts;

		[System.Xml.Serialization.XmlElementAttribute("powerSettings")]
		public List<powerSettingsType> PowerSettings = new List<powerSettingsType>();

		[System.Xml.Serialization.XmlElementAttribute("voltageInfo")]
		public List<voltageInfoType> VoltageInfos = new List<voltageInfoType>();

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public decimal version {
			get {
				return this.versionField;
			}
			set {
				this.versionField = value;
			}
		}
	}
	
	/// <remarks/>
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class clockInfoType {
		
		private ClockControlType clockControlField;
		
		private bool clockControlFieldSpecified;
		
		private eemTimersType eemTimersField;
		
		private eemClocksType eemClocksField;
		
		private string idField;
		
		private string refField;
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public ClockControlType clockControl {
			get {
				return this.clockControlField;
			}
			set {
				this.clockControlField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool clockControlSpecified {
			get {
				return this.clockControlFieldSpecified;
			}
			set {
				this.clockControlFieldSpecified = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public eemTimersType eemTimers {
			get {
				return this.eemTimersField;
			}
			set {
				this.eemTimersField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public eemClocksType eemClocks {
			get {
				return this.eemClocksField;
			}
			set {
				this.eemClocksField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string id {
			get {
				return this.idField;
			}
			set {
				this.idField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string @ref {
			get {
				return this.refField;
			}
			set {
				this.refField = value;
			}
		}
	}
	
	/// <remarks/>
	[System.SerializableAttribute()]
	public enum ClockControlType
	{
		GCC_NONE,
		GCC_STANDARD,
		GCC_STANDARD_I,
		GCC_EXTENDED,
	}
	
	/// <remarks/>
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class eemTimersType {
		
		private eemTimerType[] eemTimerField;
		
		private string idField;
		
		private string refField;
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("eemTimer", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public eemTimerType[] eemTimer {
			get {
				return this.eemTimerField;
			}
			set {
				this.eemTimerField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string id {
			get {
				return this.idField;
			}
			set {
				this.idField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string @ref {
			get {
				return this.refField;
			}
			set {
				this.refField = value;
			}
		}
	}
	
	/// <remarks/>
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class eemTimerType {
		
		private string nameField;
		
		private string valueField;
		
		private Bool defaultStopField;
		
		private bool defaultStopFieldSpecified;
		
		private decimal indexField;
		
		private bool indexFieldSpecified;
		
		private string refField;
		
		private string idField;
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string Name {
			get {
				return this.nameField;
			}
			set {
				this.nameField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string Value {
			get {
				return this.valueField;
			}
			set {
				this.valueField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public Bool defaultStop {
			get {
				return this.defaultStopField;
			}
			set {
				this.defaultStopField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool defaultStopSpecified {
			get {
				return this.defaultStopFieldSpecified;
			}
			set {
				this.defaultStopFieldSpecified = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public decimal index {
			get {
				return this.indexField;
			}
			set {
				this.indexField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool indexSpecified {
			get {
				return this.indexFieldSpecified;
			}
			set {
				this.indexFieldSpecified = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string @ref {
			get {
				return this.refField;
			}
			set {
				this.refField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string id {
			get {
				return this.idField;
			}
			set {
				this.idField = value;
			}
		}
	}
	
	/// <remarks/>
	[System.SerializableAttribute()]
	public enum Bool {
		
		/// <remarks/>
		@true,
		
		/// <remarks/>
		@false,
	}
	
	/// <remarks/>
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class deviceType {
		
		private string descriptionField;
		
		private idCodeType idCodeField;
		
		private idCodeType idMaskField;
		
		private psaType psaField;
		
		private bool psaFieldSpecified;
		
		private decimal bitsField;
		
		private bool bitsFieldSpecified;
		
		private ArchitectureType architectureField;
		
		private bool architectureFieldSpecified;
		
		private clockInfoType clockInfoField;
		
		private voltageInfoType voltageInfoField;
		
		private featuresType featuresField;
		
		private extFeaturesType extFeaturesField;
		
		private EemType eemField;
		
		private bool eemFieldSpecified;
		
		private powerSettingsType powerSettingsField;
		
		private funcletMapType funcletMapField;
		
		private functionMapType functionMapField;
		
		private memoryLayoutType memoryLayoutField;
		
		private string idField;
		
		private string refField;
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string description {
			get {
				return this.descriptionField;
			}
			set {
				this.descriptionField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public idCodeType idCode {
			get {
				return this.idCodeField;
			}
			set {
				this.idCodeField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public idCodeType idMask {
			get {
				return this.idMaskField;
			}
			set {
				this.idMaskField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public psaType psa {
			get {
				return this.psaField;
			}
			set {
				this.psaField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool psaSpecified {
			get {
				return this.psaFieldSpecified;
			}
			set {
				this.psaFieldSpecified = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public decimal bits {
			get {
				return this.bitsField;
			}
			set {
				this.bitsField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool bitsSpecified {
			get {
				return this.bitsFieldSpecified;
			}
			set {
				this.bitsFieldSpecified = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public ArchitectureType architecture {
			get {
				return this.architectureField;
			}
			set {
				this.architectureField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool architectureSpecified {
			get {
				return this.architectureFieldSpecified;
			}
			set {
				this.architectureFieldSpecified = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public clockInfoType clockInfo {
			get {
				return this.clockInfoField;
			}
			set {
				this.clockInfoField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public voltageInfoType voltageInfo {
			get {
				return this.voltageInfoField;
			}
			set {
				this.voltageInfoField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public featuresType features {
			get {
				return this.featuresField;
			}
			set {
				this.featuresField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public extFeaturesType extFeatures {
			get {
				return this.extFeaturesField;
			}
			set {
				this.extFeaturesField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public EemType eem {
			get {
				return this.eemField;
			}
			set {
				this.eemField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool eemSpecified {
			get {
				return this.eemFieldSpecified;
			}
			set {
				this.eemFieldSpecified = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public powerSettingsType powerSettings {
			get {
				return this.powerSettingsField;
			}
			set {
				this.powerSettingsField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public funcletMapType funcletMap {
			get {
				return this.funcletMapField;
			}
			set {
				this.funcletMapField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public functionMapType functionMap {
			get {
				return this.functionMapField;
			}
			set {
				this.functionMapField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public memoryLayoutType memoryLayout {
			get {
				return this.memoryLayoutField;
			}
			set {
				this.memoryLayoutField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string id {
			get {
				return this.idField;
			}
			set {
				this.idField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string @ref {
			get {
				return this.refField;
			}
			set {
				this.refField = value;
			}
		}
	}
	
	/// <remarks/>
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class idCodeType {
		
		private string versionField;
		
		private string subversionField;
		
		private string revisionField;
		
		private string maxRevisionField;
		
		private string fabField;
		
		private string selfField;
		
		private string configField;
		
		private string fusesField;
		
		private string activationKeyField;
		
		private string idField;
		
		private string refField;
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string version {
			get {
				return this.versionField;
			}
			set {
				this.versionField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string subversion {
			get {
				return this.subversionField;
			}
			set {
				this.subversionField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string revision {
			get {
				return this.revisionField;
			}
			set {
				this.revisionField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string maxRevision {
			get {
				return this.maxRevisionField;
			}
			set {
				this.maxRevisionField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string fab {
			get {
				return this.fabField;
			}
			set {
				this.fabField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string self {
			get {
				return this.selfField;
			}
			set {
				this.selfField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string config {
			get {
				return this.configField;
			}
			set {
				this.configField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string fuses {
			get {
				return this.fusesField;
			}
			set {
				this.fusesField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string activationKey {
			get {
				return this.activationKeyField;
			}
			set {
				this.activationKeyField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string id {
			get {
				return this.idField;
			}
			set {
				this.idField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string @ref {
			get {
				return this.refField;
			}
			set {
				this.refField = value;
			}
		}
	}
	
	/// <remarks/>
	[System.SerializableAttribute()]
	public enum psaType {
		
		/// <remarks/>
		Regular,
		
		/// <remarks/>
		Enhanced,
	}
	
	/// <remarks/>
	[System.SerializableAttribute()]
	public enum ArchitectureType {
		
		/// <remarks/>
		Cpu,
		
		/// <remarks/>
		CpuX,
		
		/// <remarks/>
		CpuXv2,
	}
	
	/// <remarks/>
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class voltageInfoType {
		
		private ushort vccMinField;
		
		private bool vccMinFieldSpecified;
		
		private ushort vccMaxField;
		
		private bool vccMaxFieldSpecified;
		
		private ushort vccFlashMinField;
		
		private bool vccFlashMinFieldSpecified;
		
		private ushort vccSecureMinField;
		
		private bool vccSecureMinFieldSpecified;
		
		private ushort vppSecureMinField;
		
		private bool vppSecureMinFieldSpecified;
		
		private ushort vppSecureMaxField;
		
		private bool vppSecureMaxFieldSpecified;
		
		private Bool testVppField;
		
		private bool testVppFieldSpecified;
		
		private string idField;
		
		private string refField;
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public ushort vccMin {
			get {
				return this.vccMinField;
			}
			set {
				this.vccMinField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool vccMinSpecified {
			get {
				return this.vccMinFieldSpecified;
			}
			set {
				this.vccMinFieldSpecified = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public ushort vccMax {
			get {
				return this.vccMaxField;
			}
			set {
				this.vccMaxField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool vccMaxSpecified {
			get {
				return this.vccMaxFieldSpecified;
			}
			set {
				this.vccMaxFieldSpecified = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public ushort vccFlashMin {
			get {
				return this.vccFlashMinField;
			}
			set {
				this.vccFlashMinField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool vccFlashMinSpecified {
			get {
				return this.vccFlashMinFieldSpecified;
			}
			set {
				this.vccFlashMinFieldSpecified = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public ushort vccSecureMin {
			get {
				return this.vccSecureMinField;
			}
			set {
				this.vccSecureMinField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool vccSecureMinSpecified {
			get {
				return this.vccSecureMinFieldSpecified;
			}
			set {
				this.vccSecureMinFieldSpecified = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public ushort vppSecureMin {
			get {
				return this.vppSecureMinField;
			}
			set {
				this.vppSecureMinField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool vppSecureMinSpecified {
			get {
				return this.vppSecureMinFieldSpecified;
			}
			set {
				this.vppSecureMinFieldSpecified = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public ushort vppSecureMax {
			get {
				return this.vppSecureMaxField;
			}
			set {
				this.vppSecureMaxField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool vppSecureMaxSpecified {
			get {
				return this.vppSecureMaxFieldSpecified;
			}
			set {
				this.vppSecureMaxFieldSpecified = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public Bool testVpp {
			get {
				return this.testVppField;
			}
			set {
				this.testVppField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool testVppSpecified {
			get {
				return this.testVppFieldSpecified;
			}
			set {
				this.testVppFieldSpecified = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string id {
			get {
				return this.idField;
			}
			set {
				this.idField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string @ref {
			get {
				return this.refField;
			}
			set {
				this.refField = value;
			}
		}
	}
	
	/// <remarks/>
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class featuresType {
		
		private clockSystemType clockSystemField;
		
		private bool clockSystemFieldSpecified;
		
		private Bool lcfeField;
		
		private bool lcfeFieldSpecified;
		
		private Bool quickMemReadField;
		
		private bool quickMemReadFieldSpecified;
		
		private Bool i2CField;
		
		private bool i2CFieldSpecified;
		
		private Bool stopFllDbgField;
		
		private bool stopFllDbgFieldSpecified;
		
		private Bool hasFramField;
		
		private bool hasFramFieldSpecified;
		
		private string refField;
		
		private string idField;
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public clockSystemType clockSystem {
			get {
				return this.clockSystemField;
			}
			set {
				this.clockSystemField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool clockSystemSpecified {
			get {
				return this.clockSystemFieldSpecified;
			}
			set {
				this.clockSystemFieldSpecified = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public Bool lcfe {
			get {
				return this.lcfeField;
			}
			set {
				this.lcfeField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool lcfeSpecified {
			get {
				return this.lcfeFieldSpecified;
			}
			set {
				this.lcfeFieldSpecified = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public Bool quickMemRead {
			get {
				return this.quickMemReadField;
			}
			set {
				this.quickMemReadField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool quickMemReadSpecified {
			get {
				return this.quickMemReadFieldSpecified;
			}
			set {
				this.quickMemReadFieldSpecified = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public Bool i2c {
			get {
				return this.i2CField;
			}
			set {
				this.i2CField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool i2cSpecified {
			get {
				return this.i2CFieldSpecified;
			}
			set {
				this.i2CFieldSpecified = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public Bool stopFllDbg {
			get {
				return this.stopFllDbgField;
			}
			set {
				this.stopFllDbgField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool stopFllDbgSpecified {
			get {
				return this.stopFllDbgFieldSpecified;
			}
			set {
				this.stopFllDbgFieldSpecified = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public Bool hasFram {
			get {
				return this.hasFramField;
			}
			set {
				this.hasFramField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool hasFramSpecified {
			get {
				return this.hasFramFieldSpecified;
			}
			set {
				this.hasFramFieldSpecified = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string @ref {
			get {
				return this.refField;
			}
			set {
				this.refField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string id {
			get {
				return this.idField;
			}
			set {
				this.idField = value;
			}
		}
	}
	
	/// <remarks/>
	[System.SerializableAttribute()]
	public enum clockSystemType {
		
		/// <remarks/>
		BC_1xx,
		
		/// <remarks/>
		BC_2xx,
		
		/// <remarks/>
		FLLPLUS,
		
		/// <remarks/>
		MOD_OSC,
	}
	
	/// <remarks/>
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class extFeaturesType {
		
		private Bool tmrField;
		
		private bool tmrFieldSpecified;
		
		private Bool jtagField;
		
		private bool jtagFieldSpecified;
		
		private Bool dtcField;
		
		private bool dtcFieldSpecified;
		
		private Bool syncField;
		
		private bool syncFieldSpecified;
		
		private Bool instrField;
		
		private bool instrFieldSpecified;
		
		private Bool _1377Field;
		
		private bool _1377FieldSpecified;
		
		private Bool psachField;
		
		private bool psachFieldSpecified;
		
		private Bool eemInaccessibleInLPMField;
		
		private bool eemInaccessibleInLPMFieldSpecified;
		
		private string refField;
		
		private string idField;
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public Bool tmr {
			get {
				return this.tmrField;
			}
			set {
				this.tmrField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool tmrSpecified {
			get {
				return this.tmrFieldSpecified;
			}
			set {
				this.tmrFieldSpecified = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public Bool jtag {
			get {
				return this.jtagField;
			}
			set {
				this.jtagField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool jtagSpecified {
			get {
				return this.jtagFieldSpecified;
			}
			set {
				this.jtagFieldSpecified = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public Bool dtc {
			get {
				return this.dtcField;
			}
			set {
				this.dtcField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool dtcSpecified {
			get {
				return this.dtcFieldSpecified;
			}
			set {
				this.dtcFieldSpecified = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public Bool sync {
			get {
				return this.syncField;
			}
			set {
				this.syncField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool syncSpecified {
			get {
				return this.syncFieldSpecified;
			}
			set {
				this.syncFieldSpecified = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public Bool instr {
			get {
				return this.instrField;
			}
			set {
				this.instrField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool instrSpecified {
			get {
				return this.instrFieldSpecified;
			}
			set {
				this.instrFieldSpecified = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public Bool _1377 {
			get {
				return this._1377Field;
			}
			set {
				this._1377Field = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool _1377Specified {
			get {
				return this._1377FieldSpecified;
			}
			set {
				this._1377FieldSpecified = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public Bool psach {
			get {
				return this.psachField;
			}
			set {
				this.psachField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool psachSpecified {
			get {
				return this.psachFieldSpecified;
			}
			set {
				this.psachFieldSpecified = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public Bool eemInaccessibleInLPM {
			get {
				return this.eemInaccessibleInLPMField;
			}
			set {
				this.eemInaccessibleInLPMField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool eemInaccessibleInLPMSpecified {
			get {
				return this.eemInaccessibleInLPMFieldSpecified;
			}
			set {
				this.eemInaccessibleInLPMFieldSpecified = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string @ref {
			get {
				return this.refField;
			}
			set {
				this.refField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string id {
			get {
				return this.idField;
			}
			set {
				this.idField = value;
			}
		}
	}
	
	/// <remarks/>
	[System.SerializableAttribute()]
	public enum EemType {
		
		/// <remarks/>
		EMEX_NONE,
		
		/// <remarks/>
		EMEX_LOW,
		
		/// <remarks/>
		EMEX_MEDIUM,
		
		/// <remarks/>
		EMEX_HIGH,
		
		/// <remarks/>
		EMEX_EXTRA_SMALL_5XX,
		
		/// <remarks/>
		EMEX_SMALL_5XX,
		
		/// <remarks/>
		EMEX_MEDIUM_5XX,
		
		/// <remarks/>
		EMEX_LARGE_5XX,
	}
	
	/// <remarks/>
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class powerSettingsType {
		
		private string testRegMaskField;
		
		private string testRegDefaultField;
		
		private string testRegEnableLpm5Field;
		
		private string testRegDisableLpm5Field;
		
		private string testReg3VMaskField;
		
		private string testReg3VDefaultField;
		
		private string testReg3VEnableLpm5Field;
		
		private string testReg3VDisableLpm5Field;
		
		private string idField;
		
		private string refField;
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string testRegMask {
			get {
				return this.testRegMaskField;
			}
			set {
				this.testRegMaskField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string testRegDefault {
			get {
				return this.testRegDefaultField;
			}
			set {
				this.testRegDefaultField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string testRegEnableLpm5 {
			get {
				return this.testRegEnableLpm5Field;
			}
			set {
				this.testRegEnableLpm5Field = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string testRegDisableLpm5 {
			get {
				return this.testRegDisableLpm5Field;
			}
			set {
				this.testRegDisableLpm5Field = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string testReg3VMask {
			get {
				return this.testReg3VMaskField;
			}
			set {
				this.testReg3VMaskField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string testReg3VDefault {
			get {
				return this.testReg3VDefaultField;
			}
			set {
				this.testReg3VDefaultField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string testReg3VEnableLpm5 {
			get {
				return this.testReg3VEnableLpm5Field;
			}
			set {
				this.testReg3VEnableLpm5Field = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string testReg3VDisableLpm5 {
			get {
				return this.testReg3VDisableLpm5Field;
			}
			set {
				this.testReg3VDisableLpm5Field = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string id {
			get {
				return this.idField;
			}
			set {
				this.idField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string @ref {
			get {
				return this.refField;
			}
			set {
				this.refField = value;
			}
		}
	}
	
	/// <remarks/>
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class funcletMapType {
		
		private FuncletType eraseFuncletField;
		
		private bool eraseFuncletFieldSpecified;
		
		private FuncletType writeFuncletField;
		
		private bool writeFuncletFieldSpecified;
		
		private string idField;
		
		private string refField;
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public FuncletType eraseFunclet {
			get {
				return this.eraseFuncletField;
			}
			set {
				this.eraseFuncletField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool eraseFuncletSpecified {
			get {
				return this.eraseFuncletFieldSpecified;
			}
			set {
				this.eraseFuncletFieldSpecified = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public FuncletType writeFunclet {
			get {
				return this.writeFuncletField;
			}
			set {
				this.writeFuncletField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool writeFuncletSpecified {
			get {
				return this.writeFuncletFieldSpecified;
			}
			set {
				this.writeFuncletFieldSpecified = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string id {
			get {
				return this.idField;
			}
			set {
				this.idField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string @ref {
			get {
				return this.refField;
			}
			set {
				this.refField = value;
			}
		}
	}
	
	/// <remarks/>
	[System.SerializableAttribute()]
	public enum FuncletType {
		
		/// <remarks/>
		EraseDCO,
		
		/// <remarks/>
		EraseXDCO,
		
		/// <remarks/>
		EraseFLL,
		
		/// <remarks/>
		EraseXFLL,
		
		/// <remarks/>
		EraseXv2,
		
		/// <remarks/>
		EraseXv2FRAM,
		
		/// <remarks/>
		EraseFR41xx,
		
		/// <remarks/>
		WriteDCO,
		
		/// <remarks/>
		WriteXDCO,
		
		/// <remarks/>
		Write430I,
		
		/// <remarks/>
		WriteFLL,
		
		/// <remarks/>
		WriteXFLL,
		
		/// <remarks/>
		WriteXv2,
		
		/// <remarks/>
		WriteXv2FRAM,
		
		/// <remarks/>
		WriteXv2Word,
	}
	
	/// <remarks/>
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class functionMapType {
		
		private System.Xml.XmlElement[] itemsField;
		
		private string idField;
		
		private string refField;
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAnyElementAttribute()]
		public System.Xml.XmlElement[] Items {
			get {
				return this.itemsField;
			}
			set {
				this.itemsField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string id {
			get {
				return this.idField;
			}
			set {
				this.idField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string @ref {
			get {
				return this.refField;
			}
			set {
				this.refField = value;
			}
		}
	}
	
	/// <remarks/>
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class memoryLayoutType {
		
		private MemoryType[] memoryField;
		
		private string idField;
		
		private string refField;
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("memory", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public MemoryType[] memory {
			get {
				return this.memoryField;
			}
			set {
				this.memoryField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string id {
			get {
				return this.idField;
			}
			set {
				this.idField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string @ref {
			get {
				return this.refField;
			}
			set {
				this.refField = value;
			}
		}
	}
	
	/// <remarks/>
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class MemoryType {
		
		private MemoryTypeType typeField;
		
		private bool typeFieldSpecified;
		
		private decimal bitsField;
		
		private bool bitsFieldSpecified;
		
		private string startField;
		
		private string sizeField;
		
		private string segmentSizeField;
		
		private sbyte banksField;
		
		private bool banksFieldSpecified;
		
		private Bool mappedField;
		
		private bool mappedFieldSpecified;
		
		private string maskField;
		
		private Bool protectableField;
		
		private bool protectableFieldSpecified;
		
		private memoryAccessType memoryAccessField;
		
		private string idField;
		
		private string refField;
		
		private MemoryNameType nameField;
		
		private bool nameFieldSpecified;
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public MemoryTypeType type {
			get {
				return this.typeField;
			}
			set {
				this.typeField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool typeSpecified {
			get {
				return this.typeFieldSpecified;
			}
			set {
				this.typeFieldSpecified = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public decimal bits {
			get {
				return this.bitsField;
			}
			set {
				this.bitsField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool bitsSpecified {
			get {
				return this.bitsFieldSpecified;
			}
			set {
				this.bitsFieldSpecified = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string start {
			get {
				return this.startField;
			}
			set {
				this.startField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string size {
			get {
				return this.sizeField;
			}
			set {
				this.sizeField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string segmentSize {
			get {
				return this.segmentSizeField;
			}
			set {
				this.segmentSizeField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public sbyte banks {
			get {
				return this.banksField;
			}
			set {
				this.banksField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool banksSpecified {
			get {
				return this.banksFieldSpecified;
			}
			set {
				this.banksFieldSpecified = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public Bool mapped {
			get {
				return this.mappedField;
			}
			set {
				this.mappedField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool mappedSpecified {
			get {
				return this.mappedFieldSpecified;
			}
			set {
				this.mappedFieldSpecified = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string mask {
			get {
				return this.maskField;
			}
			set {
				this.maskField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public Bool protectable {
			get {
				return this.protectableField;
			}
			set {
				this.protectableField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool protectableSpecified {
			get {
				return this.protectableFieldSpecified;
			}
			set {
				this.protectableFieldSpecified = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public memoryAccessType memoryAccess {
			get {
				return this.memoryAccessField;
			}
			set {
				this.memoryAccessField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string id {
			get {
				return this.idField;
			}
			set {
				this.idField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string @ref {
			get {
				return this.refField;
			}
			set {
				this.refField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public MemoryNameType name {
			get {
				return this.nameField;
			}
			set {
				this.nameField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool nameSpecified {
			get {
				return this.nameFieldSpecified;
			}
			set {
				this.nameFieldSpecified = value;
			}
		}
	}
	
	/// <remarks/>
	[System.SerializableAttribute()]
	public enum MemoryTypeType {
		
		/// <remarks/>
		Flash,
		
		/// <remarks/>
		Ram,
		
		/// <remarks/>
		Rom,
		
		/// <remarks/>
		Register,
	}
	
	/// <remarks/>
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class memoryAccessType {
		
		private memoryAccessClassType typeField;
		
		private Bool mpuField;
		
		private bool mpuFieldSpecified;
		
		private WriteProtectionType writeProtectionField;
		
		private string idField;
		
		private string refField;
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public memoryAccessClassType type {
			get {
				return this.typeField;
			}
			set {
				this.typeField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public Bool mpu {
			get {
				return this.mpuField;
			}
			set {
				this.mpuField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool mpuSpecified {
			get {
				return this.mpuFieldSpecified;
			}
			set {
				this.mpuFieldSpecified = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public WriteProtectionType writeProtection {
			get {
				return this.writeProtectionField;
			}
			set {
				this.writeProtectionField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string id {
			get {
				return this.idField;
			}
			set {
				this.idField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string @ref {
			get {
				return this.refField;
			}
			set {
				this.refField = value;
			}
		}
	}
	
	/// <remarks/>
	[System.SerializableAttribute()]
	public enum memoryAccessClassType
	{
		LockableRamMemoryAccess,
		BootcodeRomAccess,
		RegisterAccess5xx,
		InformationFlashAccess,
		FlashMemoryAccess2ByteAligned,
		BslFlashAccess,
		FramMemoryAccessBase,
		FramMemoryAccessFRx9,
		UsbRamAccess,
		BslRomAccess,
		BslRomAccessGR,
		TinyRandomMemoryAccess,
	}
	
	/// <remarks/>
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class WriteProtectionType {
		
		private string registerField;
		
		private string bitsField;
		
		private string maskField;
		
		private string pwdField;
		
		private string idField;
		
		private string refField;
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string register {
			get {
				return this.registerField;
			}
			set {
				this.registerField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string bits {
			get {
				return this.bitsField;
			}
			set {
				this.bitsField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string mask {
			get {
				return this.maskField;
			}
			set {
				this.maskField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string pwd {
			get {
				return this.pwdField;
			}
			set {
				this.pwdField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string id {
			get {
				return this.idField;
			}
			set {
				this.idField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string @ref {
			get {
				return this.refField;
			}
			set {
				this.refField = value;
			}
		}
	}
	
	/// <remarks/>
	[System.SerializableAttribute()]
	public enum MemoryNameType
	{
		None,
		Main,
		Info,
		Bsl,
		Bsl2,
		BootCode,
		BootCode2,
		Ram,
		Ram2,
		TinyRam,
		UsbRam,
		Lcd,
		Cpu,
		Eem,
		[System.Xml.Serialization.XmlEnumAttribute("Cpu")]
		Cpu1,
		Peripheral8bit,
		Peripheral16bit,
		Peripheral16bit1,
		Peripheral16bit2,
		Peripheral16bit3,
		IrVec,
		Lib,
		LeaPeripheral,
		LeaRam,
		MidRom,
		UssPeripheral,
	}
	
	/// <remarks/>
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class eemClockType {
		
		private decimal indexField;
		
		private string valueField;
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public decimal index {
			get {
				return this.indexField;
			}
			set {
				this.indexField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlTextAttribute()]
		public string Value {
			get {
				return this.valueField;
			}
			set {
				this.valueField = value;
			}
		}
	}
	
	/// <remarks/>
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class eemClocksType {
		
		private eemClockType[] eemClockField;
		
		private string refField;
		
		private string idField;
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("eemClock", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public eemClockType[] eemClock {
			get {
				return this.eemClockField;
			}
			set {
				this.eemClockField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string @ref {
			get {
				return this.refField;
			}
			set {
				this.refField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string id {
			get {
				return this.idField;
			}
			set {
				this.idField = value;
			}
		}
	}
	
	/// <remarks/>
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class ImportType {
		
		private string fileField;
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string file {
			get {
				return this.fileField;
			}
			set {
				this.fileField = value;
			}
		}
	}
	
	/// <remarks/>
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
	public enum ItemsChoiceType
	{
		clockInfo,
		device,
		eem,
		eemClocks,
		eemTimer,
		eemTimers,
		extFeatures,
		features,
		funcletMap,
		functionMap,
		idCode,
		idMask,
		import,
		memory,
		memoryLayout,
		powerSettings,
		voltageInfo,
	}
}
