#!/usr/bin/env python3
"""Convert one or more binary files into a C source file with byte arrays.

Each input .bin file becomes a const unsigned char array with the same name
(stripping directory and extension). Arrays are decorated with
__attribute__((section(".rodata.funclet"))) so the linker places them in the
funclet section.

Usage:
    python bin2c.py input1.bin [input2.bin ...] output.c
"""

import os
import sys


def bin2c(input_paths, output_path):
    entries = []
    for path in input_paths:
        basename = os.path.splitext(os.path.basename(path))[0]
        with open(path, 'rb') as f:
            data = f.read()
        entries.append((basename, data))

    with open(output_path, 'w') as out:
        out.write('// Automatically generated by bin2c.py -- do not edit\n')
        out.write('#include <stdint.h>\n\n')

        for name, data in entries:
            out.write(
                '__attribute__((section(".rodata.funclet")))\n'
                'const unsigned char %s[] = {\n' % name
            )
            for i in range(0, len(data), 12):
                chunk = data[i:i+12]
                hexvals = ', '.join('0x%02x' % b for b in chunk)
                out.write('    %s,\n' % hexvals)
            out.write('};\n')
            out.write(
                'const unsigned int %s_len = %d;\n\n' % (name, len(data))
            )

    print('Generated %s (%d arrays)' % (output_path, len(entries)))


if __name__ == '__main__':
    if len(sys.argv) < 3:
        print('Usage: bin2c.py input.bin [input2.bin ...] output.c')
        sys.exit(1)
    bin2c(sys.argv[1:-1], sys.argv[-1])
