
#include "stdproj.h"

#if OPT_INCLUDE_JTAG_DTRIG_

#include "JtagDev.h"
#include "util/WaveSet.h"
#include "util/DtrigJtag.h"

using namespace Bmt::Dma;
using namespace Bmt::Timer;
using namespace JtagFrame;
using namespace WaveJtag;


/// CNT preset values that align TIM1's first TMS toggle event with the correct SPI bit edge.
/// Tune these per speed grade with a logic analyzer; default 0 is a safe starting point.
static constexpr uint16_t kDtrigCntOffset_1 = 2; ///< 0.5625 MHz
static constexpr uint16_t kDtrigCntOffset_2 = 2; ///< 1.125 MHz
static constexpr uint16_t kDtrigCntOffset_3 = 2; ///< 2.25 MHz
static constexpr uint16_t kDtrigCntOffset_4 = 4; ///< 4.5 MHz
static constexpr uint16_t kDtrigCntOffset_5 = 4; ///< 9 MHz


// ── SPI device templates (one per speed grade) ───────────────────────────────

template<const uint32_t SPEED>
struct SpiJtagDevType
	: Spi::SpiTemplate
		<
		kSpiForJtag
		, SysClk
		, SPEED
		, Spi::Role::kMaster
		, Spi::ClkPol::kMode3	// CPOL=1 CPHA=1: SCK idles high, data sampled on falling edge
		, Spi::Bits::k8
		, Spi::Props::kDefault
		, Spi::BiDi::kFullDuplex
		>
{
	typedef Spi::SpiTemplate<
		kSpiForJtag
		, SysClk
		, SPEED
		, Spi::Role::kMaster
		, Spi::ClkPol::kMode3
		, Spi::Bits::k8
		, Spi::Props::kDefault
		, Spi::BiDi::kFullDuplex
	> BASE;
	static_assert(BASE::kInputClock_ / 8 >= SPEED, "Clock speed out of range");
};


// General access to SPI device (slowest speed)
using SpiJtagDev = SpiJtagDevType<JTCK_Speed_1>;


// ── DtrigJtag type aliases ────────────────────────────────────────────────────
//
// Parameters: SysClk, kTim, kTms(CH2), kTmsRld1(CH3), kTmsRld2(CH4), SpiDev, kFreq, Scan, NumBits
//
// DMA channel assignments:
//   SPI1_RX → DMA1_CH2   (JTDO receive)
//   SPI1_TX → DMA1_CH3   (JTDI transmit)
//   TIM1_CH3 → DMA1_CH6  (kTmsRld1: reloads CCR2 at entry end)
//   TIM1_CH4 → DMA1_CH4  (kTmsRld2: reloads CCR2 at exit end)
//   TIM1_CH2N → PB14     (JTMS toggle output, no DMA)

// GoIdle uses grade-1 SPI (slow, safe for TAP reset from any state)
using DtrigGoIdle = DtrigJtag<SysClk, kWaveJtagTimer, kWaveJtagTms, kWaveJtagTmsRld1, 
	SpiJtagDev, JTCK_Speed_1, Scan::kGoIdle, NumBits::kGoIdle>;

// All scan types use grade-1 template for Start/Wait/GetResult — the actual SPI
// baud rate is configured at open time via the appropriate DtrigInit_N::Init().
using DtrigIr8  = DtrigJtag<SysClk, kWaveJtagTimer, kWaveJtagTms, kWaveJtagTmsRld1, 
	SpiJtagDev, JTCK_Speed_1, Scan::kIR, NumBits::k8>;
using DtrigDr8  = DtrigJtag<SysClk, kWaveJtagTimer, kWaveJtagTms, kWaveJtagTmsRld1, 
	SpiJtagDev, JTCK_Speed_1, Scan::kDR, NumBits::k8>;
using DtrigDr16 = DtrigJtag<SysClk, kWaveJtagTimer, kWaveJtagTms, kWaveJtagTmsRld1, 
	SpiJtagDev, JTCK_Speed_1, Scan::kDR, NumBits::k16>;
using DtrigDr20 = DtrigJtag<SysClk, kWaveJtagTimer, kWaveJtagTms, kWaveJtagTmsRld1, 
	SpiJtagDev, JTCK_Speed_1, Scan::kDR, NumBits::k20>;
using DtrigDr32 = DtrigJtag<SysClk, kWaveJtagTimer, kWaveJtagTms, kWaveJtagTmsRld1, 
	SpiJtagDev, JTCK_Speed_1, Scan::kDR, NumBits::k32>;

// Per-grade Init-only instantiations: each sets TIM1 PSC and SPI BAUD for its grade
using DtrigInit_1 = DtrigJtag<SysClk, kWaveJtagTimer, kWaveJtagTms, kWaveJtagTmsRld1, 
	SpiJtagDev,  JTCK_Speed_1, Scan::kDR, NumBits::k8>;
using DtrigInit_2 = DtrigJtag<SysClk, kWaveJtagTimer, kWaveJtagTms, kWaveJtagTmsRld1, 
	SpiJtagDevType<JTCK_Speed_2>, JTCK_Speed_2, Scan::kDR, NumBits::k8>;
using DtrigInit_3 = DtrigJtag<SysClk, kWaveJtagTimer, kWaveJtagTms, kWaveJtagTmsRld1, 
	SpiJtagDevType<JTCK_Speed_3>, JTCK_Speed_3, Scan::kDR, NumBits::k8>;
using DtrigInit_4 = DtrigJtag<SysClk, kWaveJtagTimer, kWaveJtagTms, kWaveJtagTmsRld1, 
	SpiJtagDevType<JTCK_Speed_4>, JTCK_Speed_4, Scan::kDR, NumBits::k8>;
using DtrigInit_5 = DtrigJtag<SysClk, kWaveJtagTimer, kWaveJtagTms, kWaveJtagTmsRld1, 
	SpiJtagDevType<JTCK_Speed_5>, JTCK_Speed_5, Scan::kDR, NumBits::k8>;

// Verify DMA channel assignments — SPI1_TX/RX vs CCR2-reload channels must not overlap
static_assert(DtrigDr8::DmaCcr2Rld1::kChan_ != DtrigDr8::SpiTxDma::kChan_,
	"kWaveJtagTmsRld1 DMA conflicts with SPI TX DMA");
// Verify DMA channel assignments — SPI1_TX/RX vs CCR2-reload channels must not overlap
static_assert(DtrigDr8::DmaCcr2Rld1::kChan_ != DtrigDr8::SpiRxDma::kChan_,
	"kWaveJtagTmsRld1 DMA conflicts with SPI RX DMA");


// JTCLK is generated by clocking a precomputed bit pattern out of SPI1 MOSI
// (see util/WaveSet.h → SpiJtmsWave + g_JtmsWave). The dtrig path keeps PA7
// in SPI alt-function the entire time; only the SPI baud is bumped down for
// the TCLK burst, and SCK/JTCK is muted via GPIO during the burst. This sidesteps
// the STM32F1 alt-function mux contention on PA7 (TIM3_CH2 vs SPI1_MOSI).


// ── Static storage ────────────────────────────────────────────────────────────

// Active-grade CNT offset, updated by each OnOpen()
static uint16_t s_cnt_offset = kDtrigCntOffset_1;


// ── Hardware mode state machine ───────────────────────────────────────────────
//
// The dtrig driver multiplexes PA5/PA6/PA7 between SPI AF and GPIO modes via the bmt
// SetupPinMode() abstraction, which preserves output levels while changing pin function:
//
//   kSpi:  PA5→SPI1_SCK (JTCK), PA6→SPI1_MISO (JTDO), PA7→SPI1_MOSI (JTDI/JTCLK)
//   kGpio: PA5→JTCK GPIO out,   PA6→JTDO GPIO in,      PA7→JTDI GPIO out
//
// PB14 (JTMS) is managed separately: GPIO between frames / TIM1_CH2N during frames.
// JRST (PB0) and JTEST (PB1) are always GPIO and are not managed here.
//
// TDI no-transition rule: PA7 (JTDI/JTCLK) must not glitch during a mode switch. The
// SetupPinMode() call (which internally uses the new bmt SetupPinMode() method) ensures
// the output level is set before the pin mode changes, preventing glitches.
//
//   SPI → GPIO: PutChar(0xFF) settles MOSI=PA7 HIGH; SetupPinMode() switches to GPIO-out
//   GPIO → SPI: JTDI::Set() sets ODR; SetupPinMode() switches to SPI AF; PutChar(0xFF)
//               drives MOSI HIGH on the first bit and also settles SCK idle-HIGH.
//               The 8 resulting JTCK pulses are safe because TMS=0 keeps the TAP in RTI.

enum class HwMode : uint8_t { kOff, kGpio, kSpi };
static HwMode s_hw_mode = HwMode::kOff;


/// Switch PA5/6/7 to SPI AF mode.  Idempotent: no-op if already in SPI mode.
static ALWAYS_INLINE void AcquireSpiMode()
{
	if (s_hw_mode != HwMode::kSpi)
	{
		JTDI::Set(JTCLK::Get());		// update TDI with JTCLK
		JtagSpiOn::SetupPinMode();		// PA5→SCK, PA6→MISO, PA7→MOSI (SPI1 AF)
		s_hw_mode = HwMode::kSpi;
	}
}

/// Switch PA5/6/7 to GPIO mode.  Idempotent: no-op if already in GPIO mode.
static ALWAYS_INLINE void AcquireGpioMode()
{
	if (s_hw_mode != HwMode::kGpio)
	{
		JTDI::Set(JTCLK::Get());		// update TDI with JTCLK
		JtagGpioOn::SetupPinMode();		// PA5→JTCK, PA6→JTDO in, PA7→JTDI
		s_hw_mode = HwMode::kGpio;
	}
}

/// Switch PB14 back to GPIO output mode (required before bit-bang TMS operations).
/// Called after any DtrigXxx::Wait() when GPIO control of TMS is needed.
static ALWAYS_INLINE void AcquireTmsPwm()
{
	JTMS_PWM::SetupPinMode();
}

/// Switch PB14 back to GPIO output mode (required before bit-bang TMS operations).
/// Called after any DtrigXxx::Wait() when GPIO control of TMS is needed.
static ALWAYS_INLINE void AcquireTmsGpio()
{
	JTMS::SetupPinMode();
}

class MuteSpiClk
{
  public:
	ALWAYS_INLINE MuteSpiClk()
	{
		JTCK::SetHigh(); // SPI clk defaults; this is used while muting JTCK_SPI
		JTCK::SetupPinMode();
	}
	ALWAYS_INLINE ~MuteSpiClk()
	{
		JTCK_SPI::SetupPinMode();
	}
};


// ── Constructors ──────────────────────────────────────────────────────────────

JtagDev::JtagDev()   {}


// ── JtagDev virtual method implementations ────────────────────────────────────

bool JtagDev::OnAnticipateTms() const { return false; }


bool JtagDev::OnOpen()
{
	/*
	Workflow: Open -> ConnectJtag -> EnterTap -> ResetTap -> JTAG mode ready
			  \__/
	*/
	s_hw_mode = HwMode::kOff;
	DtrigDr32::ReleaseDma();  // clear stale DMA1_CH2/CH3 EN bits before SPI init
	s_cnt_offset = kDtrigCntOffset_1;
	DtrigInit_1::Init();
	AcquireTmsPwm();

	// JUST FOR A CASUAL TEST USING LOGIC ANALYZER
#define TEST_WITH_LOGIC_ANALYZER 0
#if TEST_WITH_LOGIC_ANALYZER
	WATCHPOINT();
	OnConnectJtag(BusSpeed::kSlowest);
	OnEnterTap();
	OnResetTap();

	OnIrShift(IR_CNTRL_SIG_RELEASE); // 0xA8
	OnFlashTclk(6);
	OnDrShift8(IR_CNTRL_SIG_RELEASE); // 0xA8
	OnFlashTclk(7);
	OnDrShift16(0x1234);
	OnFlashTclk(8);
	OnDrShift20(0x12345);
	OnFlashTclk(9);
	OnDrShift32(0x12345789);

	// Hardware buffers in tri-state...
	SetBusState(BusState::off);
	JtagOff::SetupPinMode();
	s_hw_mode = HwMode::kOff;
	while (true)
		__WFI();

#endif // TEST_WITH_LOGIC_ANALYZER

	return true;
}


void JtagDev::OnClose()
{
	JtagOff::SetupPinMode();
	SpiJtagDev::Stop();
	s_hw_mode = HwMode::kOff;
	// Hardware buffers in tri-state...
	SetBusState(BusState::off);
}


/*!
Switch PA5/PA6/PA7 to SPI AF mode and assert JTAG bus active.
*/
void JtagDev::OnConnectJtag(BusSpeed speed)
{
	/*
	Workflow: Open -> ConnectJtag -> EnterTap -> ResetTap -> JTAG mode ready
	                  \_________/
	*/

	speed_ = speed;

	// slau320: ConnectJTAG / DrvSignals
	JtagOn::Setup();
	// Hardware buffers driving sbw lines (JTAG comes after bus is acquired)
	SetBusState(BusState::sbw);
	StopWatch().Delay<Msec(10)>();
}


void JtagDev::SetSpeed(BusSpeed speed)
{
	switch (speed)
	{
	case BusSpeed::kSlowest: s_cnt_offset = kDtrigCntOffset_1; DtrigInit_1::ApplySpeed(); break;
	case BusSpeed::kSlow:    s_cnt_offset = kDtrigCntOffset_2; DtrigInit_2::ApplySpeed(); break;
	case BusSpeed::kMedium:  s_cnt_offset = kDtrigCntOffset_3; DtrigInit_3::ApplySpeed(); break;
	case BusSpeed::kFast:    s_cnt_offset = kDtrigCntOffset_4; DtrigInit_4::ApplySpeed(); break;
	case BusSpeed::kFastest: s_cnt_offset = kDtrigCntOffset_5; DtrigInit_5::ApplySpeed(); break;
	}
}


void JtagDev::OnReleaseJtag()
{
	// Ensure MOSI settles high before releasing the bus (slau320: StopJtag)
	AcquireSpiMode();
	{
		MuteSpiClk scope;
		SpiJtagDev::PutChar(0xFF);
	}
	AcquireTmsGpio();
	JTMS::SetLow();
	JTEST::SetLow();
	// Hardware buffers in tri state
	SetBusState(BusState::off);
	JtagOff::SetupPinMode();
	s_hw_mode = HwMode::kOff;
	StopWatch().Delay<Msec(10)>();
}


/*!
Enter TAP via TEST/RST reset sequence (slau320 4.2.1).
Only touches JRST (PB0) and JTEST (PB1).
*/
void JtagDev::OnEnterTap()
{
	/*
	Workflow: Open -> ConnectJtag -> EnterTap -> ResetTap -> JTAG mode ready
									 \______/
	*/

	JRST::SetLow();
	JTEST::SetLow();
	StopWatch().Delay<Msec(2)>();

	JRST::SetHigh();
	__NOP();
	JTEST::SetHigh();
	StopWatch().Delay<Msec(20)>();

	JRST::SetLow();
	StopWatch().Delay<Usec(40)>();

	JTEST::SetLow();
	StopWatch().Delay<Usec(1)>();

	JTEST::SetHigh();
	StopWatch().Delay<Msec(40)>();

	JRST::SetHigh();
	// Hardware buffers driving JTAG lines
	SetBusState(BusState::jtag);
	StopWatch().Delay<Msec(5)>();
}


/*!
Reset the JTAG TAP and perform fuse-HW check.

Uses DtrigGoIdle (SPI + TIM1_CH2N) to clock 6× TMS=1 + 1× TMS=0 for a guaranteed
Test-Logic-Reset from any JTAG state, then bit-bangs the fuse-check TMS pulses.
After DoGoIdle(), PB14 is in TIM1_CH2N AF mode; AcquireTmsGpio() restores GPIO mode
so the subsequent bit-bang operations work correctly.
*/
void JtagDev::OnResetTap()
{
	/*
	Workflow: Open -> ConnectJtag -> EnterTap -> ResetTap -> JTAG mode ready
												 \______/
	*/

	AcquireSpiMode();

	// Ensure TMS is HIGH as GPIO before Start() switches PB14 to TIM1_CH2N AF
	//JTMS::SetHigh();
	//JTMS::SetupPinMode();

	WATCHPOINT();
	DtrigGoIdle::DoGoIdle((uint8_t *)tx_buf_.GetCurrent(), kDtrigCntOffset_1);

	// DoGoIdle() leaves PB14 in TIM1_CH2N AF mode (TMS=LOW=RTI).
	// Restore GPIO control for the fuse-check bit-bang pulses.
	JTMS::SetHigh();
	AcquireTmsGpio();

	// Fuse-check TMS pulses (slau320)
	__NOP();
	JTMS::SetLow();
	StopWatch().Delay<Usec(5)>();
	JTMS::SetHigh();
	__NOP();
	JTMS::SetLow();
	StopWatch().Delay<Usec(5)>();
	JTMS::SetHigh();
	__NOP();
	JTMS::SetLow();
	AcquireTmsPwm();

	// GoIdle ran at grade-1 (slowest); ramp up to the requested speed now that
	// the TAP is in Run-Test/Idle and subsequent frames need full clock rate.
	SetSpeed(speed_);
}


uint8_t JtagDev::OnIrShift(uint8_t instruction)
{
	AcquireSpiMode();
	using R = DtrigIr8;
	uint8_t *tx = tx_buf_.GetNext();
	R::RenderTransaction(tx, JTCLK::IsHigh(), instruction);
	// Make sure last frame was sent
	R::Wait();
	tx_buf_.Step();
	rx_buf_.Step();
	uint8_t *rx = rx_buf_.GetCurrent();
	R::Start(tx, rx, s_cnt_offset);
	// TODO: return void and run async
	R::Wait();
	return static_cast<uint8_t>(R::GetResult(rx));
}


uint8_t JtagDev::OnDrShift8(uint8_t data)
{
	AcquireSpiMode();
	using R = DtrigDr8;
	uint8_t *tx = tx_buf_.GetNext();
	R::RenderTransaction(tx, JTCLK::IsHigh(), data);
	// Make sure last frame was sent
	R::Wait();
	tx_buf_.Step();
	rx_buf_.Step();
	uint8_t *rx = rx_buf_.GetCurrent();
	R::Start(tx, rx, s_cnt_offset);
	// TODO: return void and run async
	R::Wait();
	return static_cast<uint8_t>(R::GetResult(rx));
}


uint16_t JtagDev::OnDrShift16(uint16_t data)
{
	AcquireSpiMode();
	using R = DtrigDr16;
	uint8_t *tx = tx_buf_.GetNext();
	R::RenderTransaction(tx, JTCLK::IsHigh(), data);
	// Make sure last frame was sent
	R::Wait();
	tx_buf_.Step();
	rx_buf_.Step();
	uint8_t *rx = rx_buf_.GetCurrent();
	R::Start(tx, rx, s_cnt_offset);
	// TODO: return void and run async
	R::Wait();
	return static_cast<uint16_t>(R::GetResult(rx));
}


uint32_t JtagDev::OnDrShift20(uint32_t data)
{
	AcquireSpiMode();
	using R = DtrigDr20;
	uint8_t *tx = tx_buf_.GetNext();
	R::RenderTransaction(tx, JTCLK::IsHigh(), data);
	// Make sure last frame was sent
	R::Wait();
	tx_buf_.Step();
	rx_buf_.Step();
	uint8_t *rx = rx_buf_.GetCurrent();
	R::Start(tx, rx, s_cnt_offset);
	// TODO: return void and run async
	R::Wait();
	data = R::GetResult(rx);
	return ((data << 16) + (data >> 4)) & 0x000FFFFF;
}


uint32_t JtagDev::OnDrShift32(uint32_t data)
{
	AcquireSpiMode();
	using R = DtrigDr32;
	uint8_t *tx = tx_buf_.GetNext();
	R::RenderTransaction(tx, JTCLK::IsHigh(), data);
	// Make sure last frame was sent
	R::Wait();
	tx_buf_.Step();
	rx_buf_.Step();
	uint8_t *rx = rx_buf_.GetCurrent();
	R::Start(tx, rx, s_cnt_offset);
	R::Wait();
	return R::GetResult(rx);
}


/*!
Set JTCLK (= JTDI = SPI MOSI) high.

In dtrig mode, SPI SCK (PA5 = JTCK) cannot be gated independently, so sending a byte
causes 8 JTCK pulses.  This is harmless in Run-Test/Idle (TMS=0 after the last frame).
The MSB-first 0xFF byte leaves MOSI (= JTCLK) HIGH after the last bit.
*/
void JtagDev::OnSetTclk()
{
	AcquireSpiMode();
	MuteSpiClk mute_clk;
	SpiJtagDev::PutChar(0xff);
}


void JtagDev::OnClearTclk()
{
	AcquireSpiMode();
	MuteSpiClk mute_clk;
	SpiJtagDev::PutChar(0x00);
}


/*!
One TCLK rising transition (low → high).

0xF0 = 0b11110000: MOSI high for first 4 bits then low for last 4.
The falling edge of JTCK (bit 4) with MOSI=0 followed by MOSI=1 at bit 5 is the
rising edge of JTCLK seen by the MSP430.  MOSI ends HIGH after the byte.
*/
void JtagDev::OnPulseTclk()
{
	AcquireSpiMode();
	MuteSpiClk mute_clk;
	SpiJtagDev::PutChar(0xf0);
}


/*!
One TCLK falling transition (high → low → high).

0x0F = 0b00001111: MOSI low for first 4 bits, high for last 4.
MOSI ends HIGH after the byte.
*/
void JtagDev::OnPulseTclkN()
{
	AcquireSpiMode();
	MuteSpiClk mute_clk;
	SpiJtagDev::PutChar(0x0f);
}


void JtagDev::OnPulseTclk(int count)
{
	AcquireSpiMode();
	SpiJtagDev::Repeat(0xF0, count);
}


/*!
Generate high-frequency JTCLK pulses for MSP430 flash operations (~450 kHz).

PA7 stays in SPI1_MOSI alt-function the entire time. The TCLK burst is produced
by streaming a precomputed bit pattern (g_JtmsWave) at a reduced SPI baud
(kJtclkSpiClock); JTCK (PA5) is parked as GPIO-high during the burst by
MuteSpiClk so it doesn't toggle along with MOSI.
*/
void JtagDev::OnFlashTclk(uint32_t min_pulses)
{
	JTEST::SetLow();
	AcquireSpiMode();			// PA7 stays in SPI1_MOSI AF the whole time
	{
		MuteSpiClk mute;		// park JTCK (PA5) as GPIO-high during the burst
		SpiJtmsWave::Disable();
		Spi::RawSpiSpeed oldspeed = SpiJtmsWave::SetupSpeed();
		SpiJtmsWave::Enable();
		for (uint32_t pulses = 0; pulses < min_pulses; pulses += kNumPeriods)
			SpiJtmsWave::PutStream(g_JtmsWave, _countof(g_JtmsWave));
		SpiJtmsWave::DisableSafe();
		SpiJtmsWave::RestoreSpeed(oldspeed);
		SpiJtmsWave::Enable();
	}
}

#endif // OPT_INCLUDE_JTAG_DTRIG_
