
#include "stdproj.h"

#if OPT_INCLUDE_JTAG_DTRIG_

#include "JtagDev.h"
#include "util/WaveSet.h"
#include "util/DtrigJtag.h"

using namespace Bmt::Dma;
using namespace Bmt::Timer;
using namespace JtagFrame;
using namespace WaveJtag;


/// CNT preset values that align TIM1's first TMS toggle event with the correct SPI bit edge.
/// Tune these per speed grade with a logic analyzer; default 0 is a safe starting point.
static constexpr uint16_t kDtrigCntOffset_R = 10; ///< Go idle
static constexpr uint16_t kDtrigCntOffset_1 = 0; ///< 0.5625 MHz
static constexpr uint16_t kDtrigCntOffset_2 = 1; ///< 1.125 MHz
static constexpr uint16_t kDtrigCntOffset_3 = 3; ///< 2.25 MHz
static constexpr uint16_t kDtrigCntOffset_4 = 8; ///< 4.5 MHz
static constexpr uint16_t kDtrigCntOffset_5 = 17; ///< 9 MHz


// ── SPI device templates (one per speed grade) ───────────────────────────────

template<const uint32_t SPEED>
struct SpiJtagDevType
	: Spi::SpiTemplate
		<
		kSpiForJtag
		, SysClk
		, SPEED
		, Spi::Role::kMaster
		, Spi::ClkPol::kMode3	// CPOL=1 CPHA=1: SCK idles high, data sampled on falling edge
		, Spi::Bits::k8
		, Spi::Props::kDefault
		, Spi::BiDi::kFullDuplex
		>
{
	using BASE = Spi::SpiTemplate<
		kSpiForJtag
		, SysClk
		, SPEED
		, Spi::Role::kMaster
		, Spi::ClkPol::kMode3
		, Spi::Bits::k8
		, Spi::Props::kDefault
		, Spi::BiDi::kFullDuplex
	>;
	static_assert(BASE::kInputClock_ / 8 >= SPEED, "Clock speed out of range");
};


// General access to SPI device (slowest speed)
using SpiJtagDev = SpiJtagDevType<JTCK_Speed_1>;


// ── DtrigJtag type aliases ────────────────────────────────────────────────────
//
// Parameters: SysClk, kTim, kTms(CH2), kTmsRld1(CH3), kTmsRld2(CH4), SpiDev, kFreq, Scan, NumBits
//
// DMA channel assignments:
//   SPI1_RX → DMA1_CH2   (JTDO receive)
//   SPI1_TX → DMA1_CH3   (JTDI transmit)
//   TIM1_CH3 → DMA1_CH6  (kTmsRld1: reloads CCR2 at entry end)
//   TIM1_CH4 → DMA1_CH4  (kTmsRld2: reloads CCR2 at exit end)
//   TIM1_CH2N → PB14     (JTMS toggle output, no DMA)

// Platform-bound DtrigJtag: pins down everything that depends on the target board
// (timer unit, channels, complementary-output flag) so the per-frame aliases below
// only need to vary by SPI device, baud, scan type and payload width.
template <typename SpiDev, uint32_t Freq, Scan S, NumBits N>
using DtrigImpl = DtrigJtag<
	  SysClk
	, kWaveJtagTimer
	, kWaveJtagTms
	, kWaveJtagTmsRld1
	, SpiDev
	, Freq
	, S
	, N
	, kWaveJtagTmsCmpComplementary
>;

// GoIdle uses grade-1 SPI (slow, safe for TAP reset from any state)
using DtrigGoIdle = DtrigImpl<SpiJtagDev, JTCK_Speed_1, Scan::kGoIdle, NumBits::kGoIdle>;

// All scan types use grade-1 template for Start/Wait/GetResult — the actual SPI
// baud rate is configured at open time via the appropriate DtrigInit_N::Init().
using DtrigIr8  = DtrigImpl<SpiJtagDev, JTCK_Speed_1, Scan::kIR, NumBits::k8>;
using DtrigDr8  = DtrigImpl<SpiJtagDev, JTCK_Speed_1, Scan::kDR, NumBits::k8>;
using DtrigDr16 = DtrigImpl<SpiJtagDev, JTCK_Speed_1, Scan::kDR, NumBits::k16>;
using DtrigDr20 = DtrigImpl<SpiJtagDev, JTCK_Speed_1, Scan::kDR, NumBits::k20>;
using DtrigDr32 = DtrigImpl<SpiJtagDev, JTCK_Speed_1, Scan::kDR, NumBits::k32>;

// Per-grade Init-only instantiations: each sets TIM1 PSC and SPI BAUD for its grade
using DtrigInit_1 = DtrigImpl<SpiJtagDev,                 JTCK_Speed_1, Scan::kDR, NumBits::k8>;
using DtrigInit_2 = DtrigImpl<SpiJtagDevType<JTCK_Speed_2>, JTCK_Speed_2, Scan::kDR, NumBits::k8>;
using DtrigInit_3 = DtrigImpl<SpiJtagDevType<JTCK_Speed_3>, JTCK_Speed_3, Scan::kDR, NumBits::k8>;
using DtrigInit_4 = DtrigImpl<SpiJtagDevType<JTCK_Speed_4>, JTCK_Speed_4, Scan::kDR, NumBits::k8>;
using DtrigInit_5 = DtrigImpl<SpiJtagDevType<JTCK_Speed_5>, JTCK_Speed_5, Scan::kDR, NumBits::k8>;

// Verify DMA channel assignments — SPI1_TX/RX vs CCR2-reload channels must not overlap
static_assert(DtrigDr8::DmaCcr2Rld1::kChan_ != DtrigDr8::SpiTxDma::kChan_,
	"kWaveJtagTmsRld1 DMA conflicts with SPI TX DMA");
// Verify DMA channel assignments — SPI1_TX/RX vs CCR2-reload channels must not overlap
static_assert(DtrigDr8::DmaCcr2Rld1::kChan_ != DtrigDr8::SpiRxDma::kChan_,
	"kWaveJtagTmsRld1 DMA conflicts with SPI RX DMA");


// JTCLK is generated by clocking a precomputed bit pattern out of SPI1 MOSI
// (see util/WaveSet.h → SpiJtmsWave + gJtmsWave). The dtrig path keeps PA7
// in SPI alt-function the entire time; only the SPI baud is bumped down for
// the TCLK burst, and SCK/JTCK is muted via GPIO during the burst. This sidesteps
// the STM32F1 alt-function mux contention on PA7 (TIM3_CH2 vs SPI1_MOSI).


// ── Static storage ────────────────────────────────────────────────────────────

// Active-grade CNT offset, updated by each OnOpen()
static uint16_t s_cnt_offset = kDtrigCntOffset_1;


// ── Hardware mode state machine ───────────────────────────────────────────────
//
// The dtrig driver multiplexes PA5/PA6/PA7 between SPI AF and GPIO modes via the bmt
// SetupPinMode() abstraction, which preserves output levels while changing pin function:
//
//   kSpi:  PA5→SPI1_SCK (JTCK), PA6→SPI1_MISO (JTDO), PA7→SPI1_MOSI (JTDI/JTCLK)
//   kGpio: PA5→JTCK GPIO out,   PA6→JTDO GPIO in,      PA7→JTDI GPIO out
//
// PB14 (JTMS) is managed separately: GPIO between frames / TIM1_CH2N during frames.
// JRST (PB0) and JTEST (PB1) are always GPIO and are not managed here.
//
// TDI no-transition rule: PA7 (JTDI/JTCLK) must not glitch during a mode switch. The
// SetupPinMode() call (which internally uses the new bmt SetupPinMode() method) ensures
// the output level is set before the pin mode changes, preventing glitches.
//
//   SPI → GPIO: PutChar(0xFF) settles MOSI=PA7 HIGH; SetupPinMode() switches to GPIO-out
//   GPIO → SPI: JTDI::Set() sets ODR; SetupPinMode() switches to SPI AF; PutChar(0xFF)
//               drives MOSI HIGH on the first bit and also settles SCK idle-HIGH.
//               The 8 resulting JTCK pulses are safe because TMS=0 keeps the TAP in RTI.

// kSpiClkMuted: PA6/PA7 are still in SPI AF, but PA5 (SCK/JTCK) is parked as
// GPIO-high so MOSI bytes can be shifted without toggling JTCK. Consecutive
// TCLK helper calls stay in this state — only a Shift call (which needs JTCK
// clocking) trips the SCK pin back to SPI AF via AcquireSpiMode().
enum class HwMode : uint8_t { kOff, kGpio, kSpi, kSpiClkMuted };
static HwMode s_hw_mode = HwMode::kOff;


// ── Async shift implementation ────────────────────────────────────────────────
//
// Each OnXxxShift() now overlaps the *render* of the new frame with the *DMA*
// of the previous frame:
//
//   1. AcquireSpiMode  — pin-mux to SPI AF (idempotent).
//   2. RenderTransaction → buf.GetNext1()      ← pure CPU, runs while previous DMA is in flight.
//   3. WaitTransfer()                            ← blocks on previous frame's SPI RX TC + timer auto-stop.
//   4. buf.Step()                               ← advance ping-pong: GetNext1/2 ↔ GetCurrent1/2.
//   5. R::Start(tx, rx)                          ← kick new DMA, returns immediately.
//   6. Return JtagPending pointing at the new frame's RX slot.
//
// The Pending's `WaitTransfer()` inside `operator T()` blocks on *its own*
// frame; if the caller drops the Pending, the next shift's step (3) covers it.
// `s_have_in_flight_` tracks whether step (3) actually has anything to wait on
// (false on first call after OnOpen / after OnResetTap which uses its own
// Wait()), so the WaitTransfer free function is safe to call at any time.

static bool s_have_in_flight_ = false;


/// Switch PA5/6/7 to SPI AF mode.  Idempotent: no-op if already in SPI mode.
///
/// Async-shift note: this is called at the top of every OnXxxShift().  Shift→
/// shift transitions early-return (s_hw_mode already kSpi), leaving the
/// previous frame's DMA in flight so the next render can overlap with it.
/// The flip branches (kSpiClkMuted→kSpi, kGpio→kSpi, kOff→kSpi) only execute
/// after non-shift activity that has already drained any in-flight DMA, so no
/// drain is needed here.
static ALWAYS_INLINE void AcquireSpiMode()
{
	if (s_hw_mode == HwMode::kSpi)
		return;
	if (s_hw_mode == HwMode::kSpiClkMuted)
	{
		// PA6/PA7 are already SPI AF; only PA5 needs to flip back from GPIO-high to SCK.
		JTCK_SPI::SetupPinMode();
		s_hw_mode = HwMode::kSpi;
		return;
	}
	JTDI::Set(JTCLK::Get());		// update TDI with JTCLK
	JtagSpiOn::SetupPinMode();		// PA5→SCK, PA6→MISO, PA7→MOSI (SPI1 AF)
	s_hw_mode = HwMode::kSpi;
}

/// Enter SPI mode with SCK (PA5/JTCK) parked as GPIO-high.  Idempotent.
/// Used by OnSet/Clear/PulseTclk and OnFlashTclk so we can shift MOSI bytes
/// (TCLK pulses on JTDI) without producing JTCK pulses on PA5.
///
/// Async-shift note: drains any in-flight shift DMA before touching SPI/pins.
/// The previous shift may have left a DMA running (the caller dropped the
/// Pending without resolving it); a TCLK PutChar mid-DMA would clobber the
/// SPI shift register.  When nothing is in flight, JtagWaitTransfer is a
/// single branch on `s_have_in_flight_`.
static ALWAYS_INLINE void AcquireSpiClkMuted()
{
	JtagWaitTransfer();
	if (s_hw_mode == HwMode::kSpiClkMuted)
		return;
	if (s_hw_mode != HwMode::kSpi)
	{
		// Not in SPI yet — bring PA6/PA7 into SPI AF first.
		JTDI::Set(JTCLK::Get());
		JtagSpiOn::SetupPinMode();
	}
	// Park PA5 as GPIO-high (SPI SCK idles high in mode 3, so no edge).
	JTCK::SetHigh();
	JTCK::SetupPinMode();
	s_hw_mode = HwMode::kSpiClkMuted;
}

/// Switch PA5/6/7 to GPIO mode.  Idempotent: no-op if already in GPIO mode.
/// Drains any in-flight shift DMA — bit-bang access mid-DMA would race.
static ALWAYS_INLINE void AcquireGpioMode()
{
	JtagWaitTransfer();
	if (s_hw_mode != HwMode::kGpio)
	{
		JTDI::Set(JTCLK::Get());		// update TDI with JTCLK
		JtagGpioOn::SetupPinMode();		// PA5→JTCK, PA6→JTDO in, PA7→JTDI
		s_hw_mode = HwMode::kGpio;
	}
}

/// Switch PB14 back to GPIO output mode (required before bit-bang TMS operations).
/// Called after any DtrigXxx::Wait() when GPIO control of TMS is needed.
static ALWAYS_INLINE void AcquireTmsPwm()
{
	JTMS_PWM::SetupPinMode();
}

/// Switch PB14 back to GPIO output mode (required before bit-bang TMS operations).
/// Called after any DtrigXxx::Wait() when GPIO control of TMS is needed.
static ALWAYS_INLINE void AcquireTmsGpio()
{
	JTMS::SetupPinMode();
}


// ── Constructors ──────────────────────────────────────────────────────────────

JtagDev::JtagDev()   {}


// ── JtagDev virtual method implementations ────────────────────────────────────

bool JtagDev::OnOpen()
{
	/*
	Workflow: Open -> ConnectJtag -> EnterTap -> ResetTap -> JTAG mode ready
			  \__/
	*/
	s_hw_mode = HwMode::kOff;
	s_have_in_flight_ = false;	// fresh start: no DMA can be live yet
	DtrigDr32::ReleaseDma();  // clear stale DMA1_CH2/CH3 EN bits before SPI init
	s_cnt_offset = kDtrigCntOffset_1;
	DtrigInit_1::Init();
	// Ensure MOSI settles high required for fuse check
	AcquireTmsPwm();

#if OPT_TEST_WITH_LOGIC_ANALYZER_
	DoLogicAnalyzerTest();
#endif

	return true;
}


void JtagDev::OnClose()
{
	JtagWaitTransfer();		// don't tear down the SPI mid-DMA
	OnReleaseDriver();		// Init state: hardware buffers to Hi-Z, BusState::kStandby
	// Disable() clears SPE only; the SPI1 RCC clock stays on. The clock is owned
	// by the platform PeripheralEnabler (enabled once at boot) and SpiDevice::Setup()
	// — re-run by the next OnOpen() — assumes it is live: register writes (incl. SPE)
	// are dropped while the peripheral clock is gated. Stop() would gate it and
	// nothing re-enables it, so a second jtag_scan would come up with SPE=0 and hang
	// in PutChar() waiting for TXE.
	SpiJtagDev::Disable();
	s_hw_mode = HwMode::kOff;
}


/*!
Switch PA5/PA6/PA7 to SPI AF mode and assert JTAG bus active.
*/
void JtagDev::OnConnectJtag(BusSpeed speed)
{
	/*
	Workflow: Open -> ConnectJtag -> EnterTap -> ResetTap -> JTAG mode ready
	                  \_________/
	*/

	speed_ = speed;

	// slau320: ConnectJTAG / DrvSignals. JtagOn brings RST HIGH (JRST_On) and TEST
	// low, matching UIF's pre-entry state (no RST-low pre-pulse) — OnEnterTap then
	// starts from RST=H like TI _hil_Connect, and TEST stays low until the //3
	// activation. See I2031_ACQUISITION_GOLDEN_REFERENCE.md.
	JtagOn::Setup();
	// The acquisition bus state (only the RST buffer live for the TEST/RST entry
	// glitch) and its settle delay are set at the top of OnEnterTap, which always
	// follows this call and is also re-entered directly on the RstLow->RstHigh
	// retry with no intervening OnConnectJtag.
}


void JtagDev::SetSpeed(BusSpeed speed)
{
	switch (speed)
	{
	case BusSpeed::kSlowest: s_cnt_offset = kDtrigCntOffset_1; DtrigInit_1::ApplySpeed(); break;
	case BusSpeed::kSlow:    s_cnt_offset = kDtrigCntOffset_2; DtrigInit_2::ApplySpeed(); break;
	case BusSpeed::kMedium:  s_cnt_offset = kDtrigCntOffset_3; DtrigInit_3::ApplySpeed(); break;
	case BusSpeed::kFast:    s_cnt_offset = kDtrigCntOffset_4; DtrigInit_4::ApplySpeed(); break;
	case BusSpeed::kFastest: s_cnt_offset = kDtrigCntOffset_5; DtrigInit_5::ApplySpeed(); break;
	}
}


void JtagDev::OnReleaseJtag()
{
	// Close state: the buffers DRIVE the bus idle level (no Hi-Z, buffers stay
	// enabled) so weak/asymmetric target pull-ups/-downs cannot pulse the lines
	// between acquisition attempts. Full Hi-Z release is OnReleaseDriver(), called
	// only from OnClose(). slau320 StopJtag preamble: settle MOSI high, drop TMS/TEST.
	AcquireSpiClkMuted();
	SpiJtagDev::PutChar(0xFF);
	AcquireTmsGpio();
	JTMS::SetLow();
	JTEST::SetLow();
	// Buffers remain enabled; drive the JTAG idle outputs (RST=H, TEST=L, TMS=L,
	// TCK=H, TDI=H; TDO stays input). JtagOff is now the *driven* idle group, so
	// keep the full JTAG bus enabled (kJtag) — not Hi-Z — between attempts.
	SetBusState(BusState::kJtag);
	JtagOff::Setup();
	s_hw_mode = HwMode::kOff;
	StopWatch().Delay<Msec(10)>();
}


void JtagDev::OnReleaseDriver()
{
	// Init state: release the hardware buffers to Hi-Z so the target's own
	// pull-ups/-downs own the bus. Only full electrical release; not used inside
	// the acquisition retry loop (that stays in the driven Close state).
	SetBusState(BusState::kStandby);
	DriverOff::SetupPinMode();
	s_hw_mode = HwMode::kOff;
}


/*!
Reset the JTAG TAP and perform fuse-HW check.

Uses DtrigGoIdle (SPI + TIM1_CH2N) to clock 6× TMS=1 + 1× TMS=0 for a guaranteed
Test-Logic-Reset from any JTAG state, then bit-bangs the fuse-check TMS pulses.
After DoGoIdle(), PB14 is in TIM1_CH2N AF mode; AcquireTmsGpio() restores GPIO mode
so the subsequent bit-bang operations work correctly.
*/
void JtagDev::OnResetTap()
{
	/*
	Workflow: Open -> ConnectJtag -> EnterTap -> ResetTap -> JTAG mode ready
												 \______/
	*/

	JtagWaitTransfer();		// drain any leftover async shift before TAP reset
	AcquireSpiMode();

	// Ensure TMS is HIGH as GPIO before Start() switches PB14 to TIM1_CH2N AF
	//JTMS::SetHigh();
	//JTMS::SetupPinMode();

	DtrigGoIdle::DoGoIdle(buf.GetCurrent1(), kDtrigCntOffset_R);

	// DoGoIdle() leaves PB14 in TIM1_CH2N AF mode (TMS=LOW=RTI).
	// Restore GPIO control for the fuse-check bit-bang pulses.
	JTMS::SetHigh();
	AcquireTmsGpio();

	// Fuse-check TMS pulses (slau320 §2.3.1.2): exactly TWO TMS pulses, each with a
	// low phase ≥5 µs (current into TDI/TEST settles during the low phase). TMS rests
	// HIGH; the two negative pulses are the fuse check. No TCK is clocked here, so the
	// TAP stays in Run-Test/Idle (the pulses only drive the analog fuse-sense).
	StopWatch().Delay<Usec(1)>();
	JTMS::SetLow();
	StopWatch().Delay<Usec(6)>();	// fuse pulse 1 (low ≥5 µs)
	JTMS::SetHigh();
	StopWatch().Delay<Usec(1)>();
	JTMS::SetLow();
	StopWatch().Delay<Usec(6)>();	// fuse pulse 2 (low ≥5 µs)

	// Pre-arm the TMS timer output to its idle-HIGH state BEFORE handing the pin to
	// TIM AF. The preceding GoIdle frame froze OCREF LOW (its last toggle was TMS→RTI)
	// and the timer is stopped, so a bare GPIO→AF switch would surface that stale LOW
	// and drop TMS until the next frame's Start() re-forces it — a spurious third low
	// pulse of variable width on the LA. kForceActive/kForceInactive update OCREF
	// immediately even with the timer stopped, so the AF takeover stays HIGH.
	DtrigGoIdle::TmsOut::SetOutputMode(DtrigGoIdle::kIdleOutMode_);
	AcquireTmsPwm();

	// GoIdle ran at grade-1 (slowest); ramp up to the requested speed now that
	// the TAP is in Run-Test/Idle and subsequent frames need full clock rate.
	SetSpeed(speed_);
}


/// Drains the most recently issued shift's DMA, if one is still in flight.
/// Called from `JtagPending::operator T()` / `Get()` and from the start of
/// each shift body (to wait on the previous frame). Idempotent: clears the
/// in-flight flag so repeat calls are no-ops.
void JtagWaitTransfer()
{
	if (!s_have_in_flight_)
		return;
	// All shift variants share the same SPI RX DMA channel and the same TIM1
	// auto-stop flag, so any DtrigXxx::Wait() drains the in-flight frame.
	DtrigDr8::Wait();
	s_have_in_flight_ = false;
}


JtagPending<uint8_t> JtagDev::OnIrShift(Ir instruction)
{
	AcquireSpiMode();
	using R = DtrigIr8;
	uint8_t *tx = buf.GetNext1();
	R::RenderTransaction(tx, JTCLK::IsHigh(), E2I(instruction));
	JtagWaitTransfer();					// drain previous frame
	buf.Step();
	uint8_t *rx = buf.GetCurrent2();
	R::Start(tx, rx, s_cnt_offset);		// kick new DMA, return immediately
	s_have_in_flight_ = true;
	return { rx, +[](const uint8_t* p) -> uint8_t { return static_cast<uint8_t>(DtrigIr8::GetResult(p)); } };
}


JtagPending<uint8_t> JtagDev::OnDrShift8(uint8_t data)
{
	AcquireSpiMode();
	using R = DtrigDr8;
	uint8_t *tx = buf.GetNext1();
	R::RenderTransaction(tx, JTCLK::IsHigh(), data);
	JtagWaitTransfer();
	buf.Step();
	uint8_t *rx = buf.GetCurrent2();
	R::Start(tx, rx, s_cnt_offset);
	s_have_in_flight_ = true;
	return { rx, +[](const uint8_t* p) -> uint8_t { return static_cast<uint8_t>(DtrigDr8::GetResult(p)); } };
}


JtagPending<uint16_t> JtagDev::OnDrShift16(uint16_t data)
{
	AcquireSpiMode();
	using R = DtrigDr16;
	uint8_t *tx = buf.GetNext1();
	R::RenderTransaction(tx, JTCLK::IsHigh(), data);
	JtagWaitTransfer();
	buf.Step();
	uint8_t *rx = buf.GetCurrent2();
	R::Start(tx, rx, s_cnt_offset);
	s_have_in_flight_ = true;
	return { rx, +[](const uint8_t* p) -> uint16_t { return static_cast<uint16_t>(DtrigDr16::GetResult(p)); } };
}


JtagPending<uint32_t> JtagDev::OnDrShift20(uint32_t data)
{
	AcquireSpiMode();
	using R = DtrigDr20;
	uint8_t *tx = buf.GetNext1();
	R::RenderTransaction(tx, JTCLK::IsHigh(), data);
	JtagWaitTransfer();
	buf.Step();
	uint8_t *rx = buf.GetCurrent2();
	R::Start(tx, rx, s_cnt_offset);
	s_have_in_flight_ = true;
	// 20-bit DR result needs MSP430 word/byte-swap demuxing — embed in the decoder
	return { rx, +[](const uint8_t* p) -> uint32_t {
		uint32_t d = DtrigDr20::GetResult(p);
		return ((d << 16) + (d >> 4)) & 0x000FFFFF;
	} };
}


JtagPending<uint32_t> JtagDev::OnDrShift32(uint32_t data)
{
	AcquireSpiMode();
	using R = DtrigDr32;
	uint8_t *tx = buf.GetNext1();
	R::RenderTransaction(tx, JTCLK::IsHigh(), data);
	JtagWaitTransfer();
	buf.Step();
	uint8_t *rx = buf.GetCurrent2();
	R::Start(tx, rx, s_cnt_offset);
	s_have_in_flight_ = true;
	return { rx, +[](const uint8_t* p) -> uint32_t { return DtrigDr32::GetResult(p); } };
}


/*!
Set JTCLK (= JTDI = SPI MOSI) high.

In dtrig mode, SPI SCK (PA5 = JTCK) cannot be gated independently, so sending a byte
causes 8 JTCK pulses.  This is harmless in Run-Test/Idle (TMS=0 after the last frame).
The MSB-first 0xFF byte leaves MOSI (= JTCLK) HIGH after the last bit.
*/
void JtagDev::OnSetTclk()
{
	AcquireSpiClkMuted();
	SpiJtagDev::PutChar(0xff);
}


void JtagDev::OnClearTclk()
{
	AcquireSpiClkMuted();
	SpiJtagDev::PutChar(0x00);
}


/*!
One TCLK rising transition (low → high).

0xF0 = 0b11110000: MOSI high for first 4 bits then low for last 4.
The falling edge of JTCK (bit 4) with MOSI=0 followed by MOSI=1 at bit 5 is the
rising edge of JTCLK seen by the MSP430.  MOSI ends HIGH after the byte.
*/
void JtagDev::OnPulseTclk()
{
	AcquireSpiClkMuted();
	SpiJtagDev::PutChar(0xf0);
}


/*!
One TCLK falling transition (high → low → high).

0x0F = 0b00001111: MOSI low for first 4 bits, high for last 4.
MOSI ends HIGH after the byte.
*/
void JtagDev::OnPulseTclkN()
{
	AcquireSpiClkMuted();
	SpiJtagDev::PutChar(0x0f);
}


/*!
Generate high-frequency JTCLK pulses for MSP430 flash operations (~450 kHz).

PA7 stays in SPI1_MOSI alt-function the entire time. The TCLK burst is produced
by streaming a precomputed bit pattern (gJtmsWave) at a reduced SPI baud
(kJtclkSpiClock); JTCK (PA5) is parked as GPIO-high during the burst by
MuteSpiClk so it doesn't toggle along with MOSI.
*/
void JtagDev::OnFlashTclk(uint32_t min_pulses)
{
	JtagWaitTransfer();			// SpiJtmsWave reconfigures SPI1 — must not race a shift DMA
	JTEST::SetLow();
	AcquireSpiClkMuted();		// PA7 stays in SPI1_MOSI AF; PA5 parked GPIO-high
	SpiJtmsWave::Disable();
	Spi::RawSpiSpeed oldspeed = SpiJtmsWave::SetupSpeed();
	SpiJtmsWave::Enable();
	for (uint32_t pulses = 0; pulses < min_pulses; pulses += kNumPeriods)
		SpiJtmsWave::PutStream(gJtmsWave, _countof(gJtmsWave));
	SpiJtmsWave::DisableSafe();
	SpiJtmsWave::RestoreSpeed(oldspeed);
	SpiJtmsWave::Enable();		// DtrigJtag::Start() does not set SPE; restore it here
}

#endif // OPT_INCLUDE_JTAG_DTRIG_
