using Microsoft.Data.Sqlite;
using System;

namespace MkChipInfoDbV2
{
	class Program
	{
		static void Main(string[] args)
		{
			Console.WriteLine("MkChipInfoDbV2");
			if (args.Length != 2)
			{
				Console.WriteLine("ERROR: Invalid Command line!");
				Console.WriteLine("USAGE: MkChipInfoDbV2 <sqlite-db> <out-file-h>");
				Console.WriteLine("WHERE:");
				Console.WriteLine("    <sqlite-db>  : Path to the sqlite database generated by ImportDB.");
				Console.WriteLine("    <out-file-h> : Path to the Header file containing C++ compilable database data.");
			}
			else
			{
				// Open the database
				var connectionString = new SqliteConnectionStringBuilder()
				{
					DataSource = args[0],
					Mode = SqliteOpenMode.ReadWrite
				}.ToString();
				SqliteConnection conn = new SqliteConnection(connectionString);
				conn.Open();
				// Prepare data
				DatabasePrepare.Prepare(conn);
				// create header
				Render.OutputFileRenderer renderer = new Render.OutputFileRenderer(conn);
				renderer.CreateFile(args[1]);
				conn.Close();
			}
		}
	}
}
